
services:
  # 1. PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: roamrush-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roamrush_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB Database
  mongo:
    image: mongo:latest
    container_name: roamrush-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: swapnil
      MONGO_INITDB_ROOT_PASSWORD: swap123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Backend API
  backend:
    build:
      context: ./backend 
    container_name: roamrush-backend
    # restart: unless-stopped
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    environment:
      # These variables will be INJECTED into application.yaml
      DB_HOST: postgres # The service name, not 'roamrush-postgres' or 'localhost'
      DB_PORT: 5432
      DB_NAME: roamrush_db
      DB_USER: user
      DB_PASS: password
      MONGO_HOST: mongo # The service name, not 'localhost'
      MONGO_PORT: 27017
      MONGO_DB_NAME: roamrush_social
      MONGO_USER: swapnil
      MONGO_PASS: swap123
      # This is the NEW, CRITICAL part for your JWT "middleware"
      JWT_SECRET: "uGFiTq2R3YIAR7q80A+bBw/NnZJgVLc62eD9jR8cEHQ="

volumes:
  postgres_data:
  mongo_data: