
services:
  # 1. PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: roamrush-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB Database
  mongo:
    image: mongo:latest
    container_name: roamrush-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Backend API
  backend:
    build:
      context: ./backend 
    container_name: roamrush-backend
    # restart: unless-stopped
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    environment:
      # These variables will be INJECTED into application.yaml
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASS: ${MONGO_INITDB_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  # 4. Frontend App
  frontend:
    build:
      context: ./frontend
      args:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    container_name: roamrush-frontend
    ports:
      - "3000:3000" # Access your website at http://localhost:3000
    depends_on:
      - backend # Won't start until the backend is ready
volumes:
  postgres_data:
  mongo_data: